---
title: "Mobility Data"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
```

# Loading the Data

```{r}
load('/data/safegraph/safegraph.Rdata')

feb_mobility <- safegraph %>%
  filter(date >= "2020-03-01" & date <= "2020-04-30")
```

# February Baseline for Mobility

```{r}
median_daily_visits <- safegraph %>% 
  filter(date >= "2020-02-01" & date <= "2020-02-28") %>%
  group_by(postal_code) %>%
  summarize(median_visits = median(avg_visits_per_day))
```

# Change in Mobility

```{r}
change_in_mobility <- feb_mobility %>% 
  left_join(median_daily_visits, by = "postal_code") %>%
  mutate(change_in_mobility = (avg_visits_per_day - median_visits) / median_visits) 

median_change_in_mobility <- change_in_mobility %>%
  group_by(date) %>%
  summarize(median_change_in_mobility = median(change_in_mobility, na.rm = TRUE),
            Q1 = quantile(change_in_mobility, 0.25, na.rm = TRUE),
            Q3 = quantile(change_in_mobility, 0.75, na.rm = TRUE))
```

# Plotting Change in Mobility

```{r}
change_in_mobility %>%
  filter(change_in_mobility < 1) %>%
ggplot() +
  geom_violin(aes(y = as.factor(date), x = change_in_mobility), color = "orange") +
 geom_pointrange(aes(y = as.factor(date), xmin = Q1, xmax = Q3, x = median_change_in_mobility), median_change_in_mobility, color = "red") +
  xlim(-1, 1.25) + 
  labs(x = "Change in mobility relative to baseline", y = "Date")
```

