---
title: "Group 1 Census Data"
author: "Shoshana Farber"
output: html_document
---

```{r setup, include=FALSE}
library(tidycensus)
library(tigris, options(tigris_use_cache = TRUE))
library(sf)
library(tidyverse)
library(dplyr)

# install.packages("sf")
```

# Getting the ACS Data

```{r}
# census_api_key("9f57d911433df5106be7bad43607b75e36794f44", install = TRUE)

readRenviron("~/.Renviron")
```

# Figuring out the Variables

```{r}
# Insurance
load_variables(2016, "acs5") %>% filter(grepl("B27010", name)) %>% View()

# Median Income
load_variables(2016, "acs5") %>% filter(grepl("B19013", name)) %>% View()

# Race
load_variables(2016, "acs5") %>% filter(grepl("B02001", name)) %>% View()

# Households
load_variables(2016, "acs5") %>% filter(grepl("B11016", name)) %>% View()

# Commuters
load_variables(2016, "acs5") %>% filter(grepl("B08301", name)) %>% View()

# Age
load_variables(2016, "acs5") %>% filter(grepl("B01001", name)) %>% View()
```

```{r}
zipcodes <- read.csv("https://raw.githubusercontent.com/erikgregorywebb/nyc-housing/master/Data/nyc-zip-codes.csv") %>%
  mutate(GEOID = as.character(ZipCode))

master <- get_acs(geography = "zcta",
                  variables = c(total_18to34 = "B27010_018", 
                                uninsured_18to34 = "B27010_033", 
                                total_35to64 = "B27010_034", 
                                uninsured_35to64 = "B27010_050",
                                median_income = "B19013_001",
                                total_race = "B02001_001", 
                                identify_white = "B02001_002",
                                total_household = "B11016_001", 
                                fam_four_household = "B11016_005", 
                                fam_five_household = "B11016_006", 
                                fam_six_household = "B11016_007", 
                                fam_seven_plus_household = "B11016_008", 
                                nonfam_four_household = "B11016_013", 
                                nonfam_five_household = "B11016_014", 
                                nonfam_six_household = "B11016_015", 
                                nonfam_seven_plus_household = "B11016_016",
                                total_transport = "B08301_001",
                                total_public = "B08301_010", 
                                bus = "B08301_011",
                                total_age = "B01001_001", 
                                male_65to66 = "B01001_020", 
                                male_67to69 = "B01001_021", 
                                male_70to74 = "B01001_022", 
                                male_75to79 = "B01001_023", 
                                male_80to84 = "B01001_024", 
                                male_85plus = "B01001_025",
                                female_65to66 = "B01001_044", 
                                female_67to69 = "B01001_045", 
                                female_70to74 = "B01001_046", 
                                female_75to79 = "B01001_047", 
                                female_80to84 = "B01001_048", 
                                female_85plus = "B01001_049"),
                  state = "NY",
                  year = 2016,
                  geometry = TRUE) %>%
  inner_join(zipcodes, on = "GEOID") %>%
  transmute(GEOID, Borough, NAME, variable, estimate)

save(master, file = 'master.RData')
```

# Proportion of 18-64 Year Olds Uninsured

```{r}
uninsured_18to64 <- master %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  transmute(GEOID, Borough, NAME, geometry, total = total_18to34 + total_35to64, uninsured = uninsured_18to34 + uninsured_35to64) %>%
  mutate(prop = uninsured / total)

median(uninsured_18to64$prop, na.rm = TRUE)
```

```{r}
ggplot(uninsured_18to64, aes(fill = prop)) +
  geom_sf(aes(geometry = geometry)) +
  labs(title = "Proportion of 18 to 64 year olds uninsured") +
  scale_fill_distiller(palette = "YlOrRd", 
                       direction = 1) +
  theme_void()
```

# Median Income

```{r}
income <- master %>%
  filter(variable == "median_income")

mean(income$estimate, na.rm = TRUE)
```

```{r}
ggplot(income, aes(fill = estimate)) + 
  geom_sf(aes(geometry = geometry)) + 
  labs(title = "Median income") +
  scale_fill_distiller(palette = "YlGn", 
                       direction = 1) +
  theme_void()
```

# Proportion of Population Self-Identifying as White

```{r}
white <- master %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  transmute(GEOID, Borough, NAME, geometry, total = total_race, white = identify_white) %>%
  mutate(prop = white / total)

mean(white$prop, na.rm = TRUE)
```

```{r}
ggplot(white, aes(fill = prop)) + 
  geom_sf(aes(geometry = geometry)) + 
  labs(title = "Proportion of people who self-identify as white") +
  scale_fill_distiller(palette = "Purples", 
                       direction = 1) +
  theme_void()
```

# Proportion in Households of 4 or More

```{r}
household <- master %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  transmute(GEOID, Borough, NAME, geometry, total = total_household, 
            four_plus = fam_four_household + fam_five_household + fam_six_household + fam_seven_plus_household + nonfam_four_household + nonfam_five_household + nonfam_six_household + nonfam_seven_plus_household) %>%
  mutate(prop = four_plus / total)

mean(household$prop, na.rm = TRUE)
```

```{r}
ggplot(household, aes(fill = prop)) + 
  geom_sf(aes(geometry = geometry)) + 
  labs(title = "Proportion in household of 4 or more") +
  scale_fill_distiller(palette = "YlOrRd", 
                       direction = 1) +
  theme_void()
```

# Proportion that Commutes by Bus

```{r}
bus <- master %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  transmute(GEOID, Borough, NAME, geometry, total = total_transport, bus) %>%
  mutate(prop = bus / total)

mean(bus$prop, na.rm = TRUE)
```

```{r}
ggplot(bus, aes(fill = prop)) + 
  geom_sf(aes(geometry = geometry)) + 
  labs(title = "Proportion of population that commuted by bus") +
  scale_fill_distiller(palette = "YlOrRd", 
                       direction = 1) +
  theme_void()
```

# Proportion 65 and Older

```{r}
elderly <-  master %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  transmute(GEOID, Borough, NAME, geometry, total = total_age, 
            elderly = male_65to66 + male_67to69 + male_70to74 + male_75to79 + male_80to84 + male_85plus + female_65to66 + female_67to69 + female_70to74 + female_75to79 + female_80to84 + female_85plus) %>%
  mutate(prop = elderly / total)

mean(elderly$prop, na.rm = TRUE)
```

```{r}
ggplot(elderly, aes(fill = prop)) + 
  geom_sf(aes(geometry = geometry)) + 
  labs(title = "Proportion of population 65+ years in age") +
  scale_fill_distiller(palette = "YlOrRd", 
                       direction = 1) +
  theme_void()
```

# Saving Dataframes for Later Use

```{r}
save(uninsured_18to64, income, white, household, bus, elderly, file = 'ACSdata.RData')
```

